"""Generated by scripts/generate_status_v1.py. Do not edit by hand."""

from __future__ import annotations

from typing import TypedDict


class StatusV1BackendsItem(TypedDict):
    hours: float
    jobs: int
    kind: str
    name: str
    share: float


class StatusV1Month(TypedDict):
    completed: int
    failed: int
    interrupted: int
    preempted: int
    reclaimed: int


class StatusV1RecentItem(TypedDict):
    gpu_type: str
    hours: float
    member: str
    state: str
    utilization: float
    where: str


class StatusV1RunningItem(TypedDict):
    gpu_type: str
    hours: float
    member: str
    state: str
    utilization: float
    where: str


class StatusV1Week(TypedDict):
    completed: int
    failed: int
    interrupted: int
    preempted: int
    reclaimed: int


class StatusV1(TypedDict):
    backends: list[StatusV1BackendsItem]
    burn_per_day: str
    demo: bool
    dollars_reclaimed: str
    dollars_spent: str
    generated_at: str
    gpu_hours_used: str
    jobs_all_time: int
    members_all_time: int
    members_this_week: int
    month: StatusV1Month
    pilot: bool
    pool_remaining: str
    queue_7d: list[None | float]
    queue_depth: int
    recent: list[StatusV1RecentItem]
    repeat_members: int
    running: list[StatusV1RunningItem]
    running_now: int
    runway_confident: bool
    runway_days: float | None
    utilization_30d: list[None | float]
    utilization_7d: list[None | float]
    utilization_mean_30d: float
    utilization_mean_7d: float
    utilization_peak_7d: float
    week: StatusV1Week


def read_dashboard_v1(status: StatusV1) -> tuple[int, int, float, int]:
    """The fields consumed by the original public dashboard client."""
    return (
        status["queue_depth"],
        status["running_now"],
        float(status["dollars_spent"]),
        status["week"]["completed"],
    )
