"""A month of plausible club activity, generated by running the real broker.

Two things this is not. It is not fixtures hand-written into tables: every row
here is the result of `submit`, `tick`, `reclaim` and the lifecycle machine
doing their normal work against a fake backend and a simulated clock. And it is
not mixed in with real data: `seed()` builds its own database in its own
directory, so "is this row real" is answered by which file it is in rather than
by a flag every query has to remember to check.

Because it drives the real paths, the scenario is also an integration fixture:
`states_covered` reports which lifecycle states the run actually visited, and
the test asserts that it visits all of them. If a later phase adds a state and
forgets to exercise it here, that test fails.
"""

from __future__ import annotations

import dataclasses
import datetime as dt
import random
import shutil
from pathlib import Path

from ..backends.fake import FakeBackend
from ..broker import Broker, build_checkpoints
from ..clock import ManualClock
from ..config import BrokerConfig
from ..db import connect, migrate
from ..money import Currency, money
from ..states import JobState
from ..store import Store

DAY = 24 * 60 * 60.0

SEEDED = "seeded"
"""The origin tag every job in a demo database carries.

Belt and braces. The separation that matters is the separate file; this exists
so that a database someone copied somewhere is still self-describing.
"""

MARKER = "DEMO_DATA"
"""Written into the demo directory. The web app refuses to label a database as
demo data on a guess, and refuses to serve one silently as if it were real."""


@dataclasses.dataclass(frozen=True)
class SeedReport:
    directory: Path
    users: int
    jobs: int
    days: int
    states_covered: frozenset[str]
    missing_states: frozenset[str]

    @property
    def complete(self) -> bool:
        return not self.missing_states


# Names, not logins. The public page anonymises anyway, but a demo database that
# leaked a plausible-looking GitHub handle would be a bad thing to have made.
_MEMBERS = [
    ("demo-1", "First-year, one big job a week"),
    ("demo-2", "Runs a sweep every couple of days"),
    ("demo-3", "Two jobs a month, both long"),
    ("demo-4", "Heavy user, hits the cap"),
    ("demo-5", "Tried it once"),
    ("demo-6", "Joined last week"),
]

_WORK = [
    ("python train.py --model resnet50 --epochs 30", "a10g", 4.0),
    ("python finetune.py --base llama-3-8b --lora", "a100", 6.0),
    ("python sweep.py --trials 20", "t4", 3.0),
    ("python eval.py --split test", "l4", 1.5),
    ("python train.py --dataset cifar100", "a6000", 5.0),
    ("python profile_kernels.py --nsys", "a6000", 2.0),
]


def seed(
    directory: Path | str,
    *,
    days: int = 30,
    rng_seed: int = 7,
    now: dt.datetime | None = None,
    overwrite: bool = False,
) -> SeedReport:
    """Build a demo database in `directory`. Refuses to touch a real one."""
    directory = Path(directory)
    if directory.exists() and any(directory.iterdir()):
        if not (directory / MARKER).exists():
            raise RuntimeError(
                f"{directory} has files in it and no {MARKER} marker. Refusing to "
                "seed demo data over a directory that might be a real broker."
            )
        if not overwrite:
            raise RuntimeError(f"{directory} is already seeded. Pass overwrite=True to redo it.")
        shutil.rmtree(directory)
    directory.mkdir(parents=True, exist_ok=True)
    (directory / MARKER).write_text(
        "Seeded demo data, generated by gpu_broker.demo. Not real club activity.\n"
    )

    rng = random.Random(rng_seed)
    end = now or dt.datetime.now(dt.timezone.utc).replace(microsecond=0)
    clock = ManualClock(end - dt.timedelta(days=days))

    config = BrokerConfig(
        db_path=directory / "broker.sqlite3",
        pool_budget_usd=money("2500"),
        pool_budget_gpu_hours=money("720"),
        reclaim_enabled=True,
        idle_window_minutes=10.0,
        idle_grace_minutes=15.0,
        idle_min_samples=5,
    )
    conn = connect(config.db_path)
    migrate(conn)
    store = Store(conn, clock, config)

    # The backends share the broker's checkpoint store. Without it the fake has
    # nowhere to save, nothing is resumable, and an interrupted job restarts
    # from zero -- which would quietly turn the resume path in this scenario
    # into a plain requeue.
    checkpoints = build_checkpoints(config)

    cloud = FakeBackend(
        "ec2-spot",
        clock=clock,
        checkpoints=checkpoints,
        currency=Currency.USD,
        capacity={"t4": 2, "a10g": 2, "l4": 2, "a100": 1},
        tier="spot",
        startup_seconds=90.0,
    )
    lab = FakeBackend(
        "lab-a6000",
        clock=clock,
        checkpoints=checkpoints,
        currency=Currency.GPU_HOUR,
        capacity={"a6000": 2},
        tier="local",
        startup_seconds=20.0,
    )
    broker = Broker(store, [lab, cloud], config, checkpoints=checkpoints)

    for index, (user_id, _note) in enumerate(_MEMBERS):
        # A tight budget on demo-4 so the refusal path is reached honestly,
        # by a user actually running out, rather than by writing a REFUSED row.
        budget = money("60") if user_id == "demo-4" else money("400")
        broker.add_user(
            user_id,
            display_name=user_id,
            budget_usd=budget,
            budget_gpu_hours=money("40"),
        )
        if index >= 4:
            # The last two join partway through, so "members this week" is not
            # just everybody.
            continue

    submitted = 0

    def submit(user_id: str, work: tuple[str, str, float], **plan) -> object:
        nonlocal submitted
        command, gpu, hours = work
        result = broker.submit(
            user_id=user_id,
            command=command,
            gpu_type=gpu,
            hours=hours,
            origin=SEEDED,
        )
        submitted += 1
        if result.refusal is None and plan:
            backend = lab if gpu == "a6000" else cloud
            backend.plan(result.job.job_id, **plan)
        return result

    def drain(hours: float = 12.0) -> None:
        """Advance simulated time, ticking as the scheduler would."""
        ticks = max(1, int(hours * 60 / 5))
        for _ in range(ticks):
            broker.tick()
            clock.sleep(300)
            if not store.queued_jobs() and not store.active_jobs():
                return

    # --- a month of ordinary weeks -----------------------------------------
    # Each pass advances exactly one day, whether or not the queue kept the
    # scheduler busy for it. Advancing only as far as the work took would end
    # the simulation weeks short of now, and then every "this week" number on
    # the status page reads zero while the database looks full.
    for day in range(days - 2):
        day_started = clock.now()
        if day == days - 9:
            for late in _MEMBERS[4:]:
                broker.add_user(late[0], display_name=late[0])
        # demo-5 is deliberately left out: a club where every single member
        # comes back is not a club, it is a number nobody will believe.
        population = _MEMBERS[:4] if day < days - 9 else _MEMBERS[:4] + _MEMBERS[5:]
        for _ in range(rng.choice([0, 1, 1, 2, 3])):
            user_id = rng.choice(population)[0]
            work = rng.choice(_WORK)
            submit(user_id, work, run_hours=round(rng.uniform(0.4, 1.0) * work[2], 2))
        drain(rng.uniform(6.0, 14.0))
        elapsed = (clock.now() - day_started).total_seconds()
        if elapsed < DAY:
            clock.sleep(DAY - elapsed)
            broker.tick()

    # --- the scripted events -----------------------------------------------
    # A spot interruption that resumes and finishes with the right answer. This
    # is the one that matters: PREEMPTED -> RESUMING -> COMPLETED, and the
    # checkpoint model in the fake proves the work was not redone from zero.
    interrupted = submit(
        "demo-2",
        ("python train.py --model vit-base --epochs 40", "a10g", 6.0),
        total_steps=40,
        checkpoint_every=5,
    )
    # Long enough to have saved at least one checkpoint. Interrupting before the
    # first save would make this a plain requeue wearing the word "resume".
    for _ in range(22):
        broker.tick()
        clock.sleep(300)
    handle = store.get_job(interrupted.job.job_id).backend_handle
    if handle:
        cloud.interrupt(handle)
    # Ticks a minute apart through the restart. RESUMING is only visible while
    # the replacement machine is still booting, so a five-minute tick steps over
    # it and the job appears to go straight back to RUNNING.
    for _ in range(45):
        broker.tick()
        clock.sleep(60)
    drain(20.0)

    # An idle reclaim, with the samples that justify it kept on the job.
    idler = submit(
        "demo-4",
        ("python train.py --dataset imagenet", "a10g", 8.0),
        run_hours=8.0,
    )
    for _ in range(6):
        broker.tick()
        clock.sleep(300)
    cloud.set_utilization(idler.job.job_id, 1.0)
    # A minute apart, because a verdict needs `idle_min_samples` readings inside
    # `idle_window_minutes` and three-minute ticks never put five in ten minutes.
    for _ in range(25):
        broker.tick()
        clock.sleep(60)
    broker.reclaim()  # notifies; nothing is killed on the first pass
    clock.sleep(60 * 20)  # past the grace period
    for _ in range(12):
        broker.tick()
        clock.sleep(60)
    broker.reclaim()
    drain(6.0)

    # One that fails on its own, and one somebody changed their mind about.
    from ..backends.base import BackendStatus

    submit(
        "demo-3",
        ("python train.py --config broken.yaml", "t4", 2.0),
        run_hours=0.3,
        outcome=BackendStatus.FAILED,
        exit_code=1,
    )
    drain(4.0)

    cancelled = submit("demo-5", ("python train.py --quick", "l4", 2.0), run_hours=2.0)
    for _ in range(4):
        broker.tick()
        clock.sleep(300)
    broker.cancel(cancelled.job.job_id, actor="demo-5")
    drain(3.0)

    # A user who runs out of budget, refused with the shortfall named.
    submit("demo-4", ("python train.py --model llama-3-70b", "a100", 20.0))

    # --- leave the pool busy, so the page has something live on it ----------
    # Jump to just before the end of the window first. The queue is empty here,
    # so nothing is distorted by the jump, and it means the jobs still running
    # when the seed finishes have been running for minutes rather than for the
    # day and a half the scripted section happened to take.
    tail = end - dt.timedelta(minutes=50)
    if clock.now() < tail:
        clock.sleep((tail - clock.now()).total_seconds())
        broker.tick()

    for user_id, work in (("demo-1", _WORK[0]), ("demo-6", _WORK[4])):
        submit(user_id, work, run_hours=work[2])
    for _ in range(3):
        broker.tick()
        clock.sleep(300)
    submit("demo-2", _WORK[2], run_hours=3.0)
    submit("demo-3", _WORK[1], run_hours=6.0)
    broker.tick()

    visited = {row[1] for job in store.list_jobs(limit=None) for row in store.history(job.job_id)}
    everything = {str(state) for state in JobState}
    report = SeedReport(
        directory=directory,
        users=len(store.list_users()),
        jobs=submitted,
        days=days,
        states_covered=frozenset(visited),
        missing_states=frozenset(everything - visited),
    )
    broker.close()
    return report


def is_demo(directory: Path | str) -> bool:
    return (Path(directory) / MARKER).exists()
