"""Generate the frozen v1 status schema and typed client from its wire fixture."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests" / "fixtures" / "status_v1.json"
SCHEMA = ROOT / "contracts" / "status-v1.schema.json"
CLIENT = ROOT / "clients" / "status_v1.py"


def infer(value):
    if value is None:
        return {"type": "null"}
    if isinstance(value, bool):
        return {"type": "boolean"}
    if isinstance(value, int):
        return {"type": "integer"}
    if isinstance(value, float):
        return {"type": "number"}
    if isinstance(value, str):
        return {"type": "string"}
    if isinstance(value, list):
        variants = []
        for item in value:
            candidate = infer(item)
            if candidate not in variants:
                variants.append(candidate)
        items = variants[0] if len(variants) == 1 else {"anyOf": variants}
        return {"type": "array", "items": items}
    if isinstance(value, dict):
        return {
            "type": "object",
            "properties": {key: infer(item) for key, item in value.items()},
            "required": list(value),
            "additionalProperties": True,
        }
    raise TypeError(type(value))


def class_name(raw: str) -> str:
    return "".join(part.title() for part in re.split(r"[^a-zA-Z0-9]+", raw) if part)


class Emitter:
    def __init__(self):
        self.classes: list[str] = []

    def expression(self, schema: dict, name: str) -> str:
        if "anyOf" in schema:
            return " | ".join(self.expression(item, name) for item in schema["anyOf"])
        kind = schema["type"]
        if kind == "null":
            return "None"
        if kind == "boolean":
            return "bool"
        if kind == "integer":
            return "int"
        if kind == "number":
            return "float"
        if kind == "string":
            return "str"
        if kind == "array":
            return f"list[{self.expression(schema['items'], name + 'Item')}]"
        if kind == "object":
            lines = []
            for key, child in schema["properties"].items():
                lines.append(f"    {key}: {self.expression(child, name + class_name(key))}")
            self.classes.append(f"class {name}(TypedDict):\n" + "\n".join(lines))
            return name
        raise ValueError(kind)


def render(fixture: dict) -> tuple[str, str]:
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://gpu-broker.example/contracts/status-v1.schema.json",
        "title": "GPU Broker public status v1",
        "$comment": "Captured from commit f717dde. Additive fields are allowed.",
        **infer(fixture),
    }
    schema["properties"]["runway_days"] = {
        "anyOf": [{"type": "number"}, {"type": "null"}]
    }
    emitter = Emitter()
    emitter.expression(schema, "StatusV1")
    client = (
        '"""Generated by scripts/generate_status_v1.py. Do not edit by hand."""\n\n'
        "from __future__ import annotations\n\n"
        "from typing import TypedDict\n\n\n"
        + "\n\n\n".join(emitter.classes)
        + "\n\n\ndef read_dashboard_v1(status: StatusV1) -> tuple[int, int, float, int]:\n"
        "    \"\"\"The fields consumed by the original public dashboard client.\"\"\"\n"
        "    return (\n"
        "        status[\"queue_depth\"],\n"
        "        status[\"running_now\"],\n"
        "        float(status[\"dollars_spent\"]),\n"
        "        status[\"week\"][\"completed\"],\n"
        "    )\n"
    )
    return json.dumps(schema, indent=2) + "\n", client


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema, client = render(json.loads(FIXTURE.read_text()))
    if args.check:
        if not SCHEMA.exists() or SCHEMA.read_text() != schema:
            raise SystemExit("contracts/status-v1.schema.json is stale")
        if not CLIENT.exists() or CLIENT.read_text() != client:
            raise SystemExit("clients/status_v1.py is stale")
        return 0
    SCHEMA.parent.mkdir(parents=True, exist_ok=True)
    CLIENT.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA.write_text(schema)
    CLIENT.write_text(client)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
